# config/config.yaml

# General Settings

project_name: "Bible RAG System"
log_level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL

bible_file_path: "data/raw_data/AKJV.txt"
processed_bible_file_path: "data/processed_data"
processed_jsonl_file: "data/processed_data/akjv_verses.jsonl"
faiss_index_path: "faiss_index"
faiss_index_name: "bible_faiss_index"
embedding_model_name: "BAAI/bge-large-en-v1.5"
llm_model: "mistralai/Mistral-7B-Instruct-v0.1"
top_k: 5

